version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1.0"       # Limita o uso de CPU a 1 núcleo
          memory: "1g"       # Limita o uso de memória a 1GB
